#!/usr/bin/env bash

# Function to retrieve DNS information for a given domain and subdomain
get_dns_info() {
    subdomain=$1
    domain=$2
    dns_info=$(dig +short $subdomain.$domain)

    if [[ -n "$dns_info" ]]; then
        record_type=$(echo $dns_info | awk '{ print $1 }')
        destination=$(echo $dns_info | awk '{ print $2 }')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "No DNS record found for subdomain $subdomain"
    fi
}

# Check if domain argument is provided
if [[ -z "$1" ]]; then
    echo "Please provide a domain name to audit"
    exit 1
fi

# Display information for default subdomains (www, lb-01, web-01, web-02)
if [[ -z "$2" ]]; then
    get_dns_info www $1
    get_dns_info lb-01 $1
    get_dns_info web-01 $1
    get_dns_info web-02 $1
else
    # Display information for specified subdomain
    get_dns_info $2 $1
fi

exit 0
