#!/usr/bin/env bash

# Update the package list and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure nginx to listen on port 80 and return "Hello World!" at its root
sudo echo "server {
    listen 80;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
