#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Edit the default configuration file
sudo sed -i '/server_name _;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
