#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
  bind *:80
  default_backend servers

backend servers
  balance roundrobin
  server web-01 18.234.249.234:80 check
  server web-02 54.236.17.11:80 check
EOF'

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Start HAProxy
sudo service haproxy start
