#!/bin/bash

# Set localhost to 127.0.0.2
sudo sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts

# Set facebook.com to 8.8.8.8
sudo sed -i 's/157\.240\.11\.35/8.8.8.8/g' /etc/hosts

# Restart networking service
sudo service networking restart

