#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/^127.*	localhost/127.0.0.2	localhost/' ~/hosts.new
echo 8.8.8.8$'\t'facebook.com >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
